"""categoria table

Revision ID: 49d157f8d446
Revises: f8805a1432a8
Create Date: 2020-05-19 10:33:36.088014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d157f8d446'
down_revision = 'f8805a1432a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_desc'), 'categoria', ['desc'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categoria_desc'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
