"""transacao table

Revision ID: 729653f6d292
Revises: 922906b75fd8
Create Date: 2020-05-10 12:52:11.667780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729653f6d292'
down_revision = '922906b75fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=140), nullable=True),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('comprovante', sa.String(length=140), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacao_data'), 'transacao', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacao_data'), table_name='transacao')
    op.drop_table('transacao')
    # ### end Alembic commands ###
