"""conta table

Revision ID: 83f3a84f0c47
Revises: 49d157f8d446
Create Date: 2020-05-19 10:39:01.628633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f3a84f0c47'
down_revision = '49d157f8d446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    # ### end Alembic commands ###
