"""transacao table

Revision ID: 8c2dd4b3c9f9
Revises: 83f3a84f0c47
Create Date: 2020-05-19 10:41:49.268559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2dd4b3c9f9'
down_revision = '83f3a84f0c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=140), nullable=True),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('comprovante', sa.String(length=140), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacao_data'), 'transacao', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacao_data'), table_name='transacao')
    op.drop_table('transacao')
    # ### end Alembic commands ###
