"""conta table

Revision ID: 922906b75fd8
Revises: 
Create Date: 2020-05-10 12:26:39.579279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922906b75fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_conta_email'), 'conta', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conta_email'), table_name='conta')
    op.drop_table('conta')
    # ### end Alembic commands ###
