"""table contaCategoria

Revision ID: bef824a70f21
Revises: 399414079dca
Create Date: 2020-06-01 20:53:06.803680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef824a70f21'
down_revision = '399414079dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contaXcategoria', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'contaXcategoria', type_='foreignkey')
    op.create_foreign_key(None, 'contaXcategoria', 'conta', ['conta_id'], ['id'])
    op.drop_column('contaXcategoria', 'usuario_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contaXcategoria', sa.Column('usuario_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'contaXcategoria', type_='foreignkey')
    op.create_foreign_key(None, 'contaXcategoria', 'usuario', ['usuario_id'], ['id'])
    op.drop_column('contaXcategoria', 'conta_id')
    # ### end Alembic commands ###
