"""perfil table

Revision ID: f8805a1432a8
Revises: 580b331fd0f7
Create Date: 2020-05-19 10:30:31.162541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8805a1432a8'
down_revision = '580b331fd0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_desc'), 'perfil', ['desc'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfil_desc'), table_name='perfil')
    op.drop_table('perfil')
    # ### end Alembic commands ###
